### PR TITLE
switch to git repo for libsisl

### PR DESCRIPTION
**Pull request by planthaber**
pending pull request on the git repo to build with gcc6

### CODE REVIEW

**Comment by jmachowinski** [comment]
the pull request was just merged

**Comment by planthaber** [comment]
saw that, now we have to switch to actually use the git repo instaed of the tar

**Comment by jmachowinski** [comment]
Write an mail about this to the rock-users ml, and I'll merge

**Comment by planthaber** [comment]
Ah yes, this will cause the "external/sisl" is not a git repository error...
I'll write the mail.

**Comment by doudou** [comment]
Write email and then *3 hours later* merge. For a change that will make everyone's next update fail.

**Comment by doudou** [comment]
Next time you'll ask about waiting for publishing say something like autoproj 2, I'll consider how *you* handle everybody else's installation.

**Comment by planthaber** [comment]
Except this is a bugfix which makes rock build again on 16.10 and debian testing:
https://github.com/SINTEF-Geometry/SISL/pull/9

**Comment by doudou** [comment]
> Except this is a bugfix which makes rock build again on 16.10 and debian testing:

Do realize that I don't object to the change - I think it's great - but to the timing of it.

To have it working on your pet ubuntu you're ready to break everyones updates with no advance warning ... I knew that we definitely don't have the same priorities, this only confirms it.

**Comment by planthaber** [comment]
I am using the current Ubuntu because we promised rock would run on Ubuntu LTS and current version. I not particularly like using the current version and to be the one to adapt osdeps and solve bugs like these and gcc6 stuff and all the other issues. But someone has to to it.

Otherwise we should discuss to supporting only LTS Versions on the mailing list.

Time between mail and merge could have been larger, right. But that is a discussion between those who are able to merge, and i am not able to merge stuff within rock-core at all

**Comment by jmachowinski** [comment]
I don't see how this change can brick an installation. It's the same version of SISL with one additional patch. Apart from this the user needs to once delete his sisl folder and reupdate. 
The patch was checked beforehand on ubuntu 14.04 16.04 and 16.10.
Rebuilding a stack takes around 5 minutes, as everything is in ccache...

**Pull request merged**
