### PR TITLE
Removed base/orogen/interfaces and gitorious completly

### PR DESCRIPTION
**Pull request by goldhoorn**
interfaces could also be removed completly?!

### CODE REVIEW

**Comment by doudou** [comment]
> interfaces could also be removed completly?!

I would love to ...

**Comment by goldhoorn** [comment]
On 05.08.2015 15:29, Sylvain Joyeux wrote:
>
>     interfaces could also be removed completly?!
>
> I would love to ...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/package_set/pull/62#issuecomment-127997001>.
>
:+1:

*updated*

Does this fit the policy (as long as we don't have a deprecation 
system), and this package currently breaks the build?
(as asked on the ML)

-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by goldhoorn** [comment]
Other opinions from core-dev's to make a decition:

@jakobs 
@2maz

**Comment by goldhoorn** [comment]
This breaks the stable-all build, therefore i would like to have a descition on this...

**Comment by 2maz** [comment]
removal okay for me

**Comment by goldhoorn** [comment]
Ok, ack from two different core dev's i agree there too. I merge now.

**Pull request merged**
