### PR TITLE
fix qtruby on debian testing (ruby 21)

### PR DESCRIPTION
**Pull request by D-Alex**

### CODE REVIEW

**Comment by marvin2k** [comment]
+1

**Comment by doudou** [comment]
Merged. However, if a brave soul could do what is actually really needed: remove all usage of the prebuilt QtRuby packages ? ... The code in prebuilt QtRuby packages is unmaintained, as the only person doing maintenance on this codebase is the maintainer of the qtbindings gem (I found that out recently). In other words, we're regularly hitting bugs that have been fixed, just in qtbindings, not in ruby-qt4

**Comment by marvin2k** [comment]
Do you mean sifting through the osdeps and _removing_ system packages to replace them by the gem?

**Comment by doudou** [comment]
Only for qtruby, yes. This is the sorry state of qtruby's development

**Comment by marvin2k** [comment]
I could try. Well, thing is: just doing one single fresh bootstrap kept me understanding errors and creating PRs for half a day so far...

**Pull request merged**
