### PR TITLE
hard-fork orocos-toolchain packages we need for rock

### PR DESCRIPTION
**Pull request by doudou**
I've been unable to reach anyone on the orocos side for 2-3 years now
to discuss the future of ... anything really. Even RTT. I think it's time
to stop bothering.

### CODE REVIEW

**Comment by doudou** [comment]
Good questions

1. because there are still people using the orocos toolchain, who therefore happen to depend on the typelib version in orocos-toolchain/typelib. As I don't plan to support this use case (which was always not very well working in the first place), I don't want to work there. This makes it clear that I consider that typelib is a rock-core project (which, in hindsight, it always was) maintained by Rock developers.
2. because without removing the linkage, pull requests and issues end up in the original repository, which creates a lot of confusion.

**Review by g-arjones — APPROVED** [review]

**Comment by doudou** [comment]
If there is an agreement of principle, I'll change this pull request to hard-fork all the packages that are relevant to Rock, that is, in addition to rtt (which is already forked) and typelib:

- utilrb
- rtt_typelib

@planthaber, thoughts ? Are you the right person to discuss this with at DFKI ? If not, can you point me to that person ?

**Comment by planthaber** [comment]
> @planthaber, thoughts ? Are you the right person to discuss this with at DFKI ? If not, can you point me to that person ?

I'm fine with this, and yes, i am the right person now.

**Review by planthaber — APPROVED** [review]

**Comment by planthaber** [comment]
What do you think of renaming the packages to match the folder names?

e.g. orogen->tools/orogen and add metapackage to match also the old name?

Thsi whould make stuff like 'amake tools/orogen' actually work instead of `amake orgoen`

We could remove the moving of the packages here:
https://github.com/rock-core/package_set/blob/master/01import_orocos_toolchain.autobuild#L51

**Comment by doudou** [comment]
I want to go slow on this, but that's on my list, yes.

For me, the cleanup steps are:
- remove the flavor system (incl. the OCL question)
- remove the dependency on orocos.toolchain, renaming the packages to match our scheme. Add aliases from the old name to the new names.

**Pull request merged**
