### PR TITLE
Added class_loader

### PR DESCRIPTION
**Pull request by goldhoorn**
This is a moved version of PR: https://github.com/rock-core/rock-package_set/pull/36

### CODE REVIEW

**Comment by doudou** [comment]
Last one ... Please create a manifest for it (in manifests/tools/class_loader.xml)

**Comment by goldhoorn** [comment]
*updated*

**Comment by goldhoorn** [comment]
ping

**Comment by doudou** [comment]
and merged

**Comment by planthaber** [comment]
For debug builds on (at least) ubuntu 14.10 the debian package: libpocofoundation9-dbg is missing.

We can either add that one to the "poco" osdep or build the loader as "Release"

**Comment by doudou** [comment]
We're three people noticing this ... and made three different pull requests ... We all need to remember checking open issues/PRs before creating one ;-)

Anyways, I've merged #26 (acked by Matthias)

**Pull request merged**
