### PR TITLE
add dependencies related to log transfer server

### PR DESCRIPTION
**Pull request by rbtmrcs**
Dependencies needed by https://github.com/rock-core/tools-syskit/pull/275

### CODE REVIEW

**Comment by planthaber** [comment]
merging this as https://github.com/rock-core/tools-syskit/pull/275 was also merged

**Comment by planthaber** [comment]
Actually I'm getting an error while testing on 20.04: "Could not find gem 'ftpd' in rubygems repository https://rubygems.org/ or installed locally" Can you please check?

**Comment by g-arjones** [comment]
Sorry, @planthaber. I missed your comment Would you like me to revert?

**Comment by planthaber** [comment]
> Sorry, @planthaber. I missed your comment. Would you like me to revert?

Not in case it works for 18.04.

**Comment by doudou** [comment]
It does ... our CI runs 18.04.

Sorry I missed this one. Just saw the string of build failures ... :(

**Pull request merged**
